-- Supabase schema for portfolio
-- Run in SQL editor

create table projects (
  id bigint generated by default as identity primary key,
  title text,
  short text,
  description text,
  image text,
  year int,
  inserted_at timestamptz default now()
);

create table certificates (
  id bigint generated by default as identity primary key,
  title text,
  issuer text,
  file_url text,
  inserted_at timestamptz default now()
);

create table comments (
  id bigint generated by default as identity primary key,
  name text,
  body text,
  project_id bigint,
  inserted_at timestamptz default now()
);

create table contacts (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  message text,
  inserted_at timestamptz default now()
);
